ALTER TABLE lead ADD COLUMN IF NOT EXISTS storage_limit BIGINT DEFAULT 10737418240;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS allow_negative_storage BOOLEAN DEFAULT FALSE;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT FALSE;
