ALTER TABLE "user"
    ADD COLUMN IF NOT EXISTS allowance INTEGER DEFAULT 0;

ALTER TABLE "user"
    ADD COLUMN IF NOT EXISTS bhyt INTEGER DEFAULT 0;

ALTER TABLE "user"
    ADD COLUMN IF NOT EXISTS bhxh INTEGER DEFAULT 0;
