export enum HolidayType {
	PUBLIC_HOLIDAY = 'PUBLIC_HOLIDAY',
	COMPANY_HOLIDAY = 'COMPANY_HOLIDAY',
	PERSONAL_LEAVE = 'PERSONAL_LEAVE',
	SICK_LEAVE = 'SICK_LEAVE',
	ANNUAL_LEAVE = 'ANNUAL_LEAVE',
	OTHER = 'OTHER',
} 